# -*- coding: utf-8 -*-
"""
Created on Fri Mar  3 12:40:47 2023

@author: F1DY4
"""

import requests

url='https://www.hipogesworks.com/EstatesTakeoversSareb/Details/250046'

datos={
       '__RequestVerificationToken': 'gNE4l_AzBkEZqXOjIRpoPhcS31thHJCeJtXJiJ8NJ5N-Y2rDOK5NKjLCaH-bBCLBuoncuXesiLH2GtvA7jSMU9O3wj5aDEdwh0nU2UYWxMtp79e9mTyL1rdlItSlzhG20',#REQUEST TOKEN !!ES NECESARIO CAMBIAR!!
       'idEstateTakeover': 10611,
       'idEstate': 250046,
       'section': '',
       'ToSend': 0,
       'idOrder': 92471,
       'idUserFacility': 4232,
       'fullName': 'Serveo Servicios S.A.U.',
       'domiciled': 'CALLE Quintanavides Nº 21   CP. 28050 Madrid',
       'cif': 'A80241789',
       'visitDate':'',
       'visitTime':'',
       'technicianName':'',
       'TechnicianIdentityCard':'',
       'technicianPhone':'',
       'technicianEmail':'',
       'CityName': 'Mollina',
       'ProvinceName': 'Málaga',
       'RegionName': 'Andalucía',
       'ZipCode': 29532,
       'verifiedStreetType':'',
       'verifiedStreetName':'',
       'verifiedStreetNumber':'',
       'verifiedFloorNumber':'',
       'verifiedGateNumber':'',
       'verifiedStairsNumber':'',
       'verifiedDoorNumber':'',
       'verifiedLatitude':'',
       'verifiedLongitude':'',
       'FileDocument': '(binary)',
       'AddressComments':'',
       'assetType':'',
       'assetTypology':'',
       'sharedUse':'', 
       'industrialUse':'',
       'industrialUseOther':'', 
        'Category':'', 
        'Subcategory':'', 
        'Situation': '',
        'orientationType': '',
        'showcase': '',
        'numberOfFloors': '',
        'floorHeight': '',
        'aboveGroundFloors': '',
        'belowGroundFloors': '',
        'annexes': '',
        'calificationAEO': '',
        'qualification':  '',
        'Proindiviso': '',
        'ProindivisoPercent':'', 
        'TerrainEnvironment': '',
        'riskOccupationTO': '',
        'perimetralFence': '',
        'accessType': '',
        'commonAreasKeys':'', 
        'plotState': '',
        'TotalNumberEstates':'', 
        'InvolvementFee': '',
        'plotStateDescription':'', 
        'existentBuildings': '',
        'existentBuildingDescription': '',
        'constructionStatus': '',
        'conservationStatus': '',
        'constructionPercent': '',
        'finishedUrbanization': '',
        'riskPreventionReportProposal': '',
        'hasRiskPreventionReportProposal':'', 
        'estateInformationComments':'', 
        'checkedSurface': '',
        'RegistrationArea': '',
        'CadastreArea':'', 
        'M2Built': '',
        'M2Habitable': '',
        'CommonAreas': '',
        'M2Garden': '',
        'numberRooms': '',
        'numberOffices': '',
        'numberProductionAreas':'', 
        'numberBathrooms': '',
        'numberToilets': '',
        'numberLivingRooms': '',
        'numberPublicAttentionAreas':'', 
        'numberOpenWorkAreas': '',
        'numberMeetingRooms': '',
        'numberWarehouses': '',
        'numberArchives': '',
        'numberKitchens': '',
        'numberOfficesAuxiliary':'', 
        'numberShowcases': '',
        'numberReceptions': '',
        'numberOpenOfficeAreas':'', 
        'numberOffices': '',
        'numberLobbys': '',
        'numberCorridors': '',
        'numberDistributors': '',
        'numberCoveredTerraces': '',
        'numberUncoveredTerraces':'', 
        'numberCourtyards':'', 
        'numberGardens': '',
        'numberFacilitiesRooms':'', 
        'numberDocks': '',
        'numberDressingRooms':'', 
        'numberStorages': '',
        'numberGarages': '',
        'numberCoveredParkings': '',
        'numberUncoveredParkings': '',
        'numberVehicleManeuveringAreas':'', 
        'numberExternalWharehouses':'', 
        'numberExternalGardens': '',
        'numberExternalFacilitiesRooms':'', 
        'estateDescriptionComments': '',
        'AboveGroundFloorsNotMandatory': '',
        'BelowGroundFloorsNotMandatory':'', 
        'elevator': '',
        'maintenanceStatus':'', 
        'estateEnvironment':'', 
        'propertyAdministration':'', 
        'communityAmount':'', 
        'ibiAmount':'', 
        'HasCommunity':'', 
        'administratorName':'', 
        'administratorPhone':'', 
        'administratorEmail':'', 
        'neighbourName':'', 
        'neighbourPhone':'', 
        'neighbourEmail': '',
        'propertyManagementComments': '',
        'btnsave': 'Guardar cambios'
       }

Headers = { 
    
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
    'Cache-Control':   'max-age=0',
    'Connection': 'keep-alive',
    'Content-Length': '52082',
    'Content-Type': 'application/x-www-form-urlencoded',
    'Cookie': 'lang=es; __RequestVerificationToken=j4AfTUupBQzCjT5jBJXb8vmKCFERdBvPFT1vBBcPehlL_ro4WxNvQlNLJIH9zLJqqUpZauDsSYBeGlLbD1lmGEoWEzpZiVcK1GsDBu2W-401; ASP.NET_SessionId=saytokauzz0d2ej0v1c4vufw; .ASPXAUTH=E433D3F2D8ED9BEC5A64F2DEDF4CFC5BE2EC06C0ABBE1C1A89FF2A7D343A2A222E55B2C28A5E6CFFE587B3D2F976E23B46861CEE819CDEF4225C281293E4C00081B626C0187D1E5754D75ECBDD59CF75387DD3D979D3F10124644C05A25B4AE6A7D880ACDC62997FDAE4092D5F12F13D9703EA6AA6AB7061518A74A4CAB6A438',
    'Host': 'portalticketing.microsoftcrmportals.com',
    'Origin': 'https://portalticketing.microsoftcrmportals.com',
    'Referer': 'https://portalticketing.microsoftcrmportals.com/es-ES/incidencias/incidencia/?id=48a4c8da-b2b9-ed11-83ff-000d3adf72bc',
    'sec-ch-ua': '"Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': "Windows",
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'
    
    }


respuesta = requests.post(url, data=datos, headers=Headers)

texto_respuesta= respuesta.text

print(texto_respuesta)

